print("problema12")
a=int(input("Introduceti nr. de oua pe care le face prima gaina timp de o zi:"))
b=int(input("Introduceti nr. de oua pe care le face a doua gaina timp de o zi:"))
c=int(input("Introduceti nr. de oua pe care le face a treia gaina timp de o zi:"))
print("Intr-o saptamina se obtin :", 7*(a+b+c), "oua")